-- THE FOLLOWING SQLS CREATE ALL THE TABLES FOR THE EMPLOYEE DATABASE, LOAD THE DATA INTO EACH
-- TABLE USING TEH IMPORT FUNCTIONALITY

--CREATE TITLES TABLE
CREATE TABLE TITLES (title_is VARCHAR PRIMARY KEY, title VARCHAR(30));

--CREATE EMPLOYEES TABLE
CREATE TABLE EMPLOYEES (emp_no INT PRIMARY KEY,	emp_title_id VARCHAR(10), birth_date DATE, 
						first_name VARCHAR(30),last_name VARCHAR(30), sex CHAR(1), hire_date DATE);

--CREATE DEPARTMENT TABLE
CREATE TABLE DEPARTMENTS (dept_no VARCHAR(10) PRIMARY KEY, dept_name VARCHAR(30));

--CREATE DEPARTMENT_MANAGER JUNCTION TABLE
CREATE TABLE DEPARTMENT_MANAGER(dept_no VARCHAR(10), emp_no INT,
							   CONSTRAINT DEPT_NO_FK FOREIGN KEY (dept_no) REFERENCES DEPARTMENTS(dept_no),
							   CONSTRAINT EMP_NO_FK FOREIGN KEY (emp_no) REFERENCES EMPLOYEES(emp_no));

--CREATE DEPARTMENT_EMPLOYEE JUNCTION TABLE
CREATE TABLE DEPARTMENT_EMPLOYEE(emp_no INT, dept_no VARCHAR(10),
							   CONSTRAINT EMP_NO_FK FOREIGN KEY (emp_no) REFERENCES EMPLOYEES(emp_no),
							   CONSTRAINT DEPT_NO_FK FOREIGN KEY (dept_no) REFERENCES DEPARTMENTS(dept_no));

--CREATE SALARIES TABLE
CREATE TABLE SALARIES (emp_no INT, salary INT,
					  CONSTRAINT EMP_NO_FK FOREIGN KEY (emp_no) REFERENCES EMPLOYEES(emp_no));
			